pr:
  branches:
    include:
      - dev
  paths:
    exclude:
      - docs/*
      - README.md

trigger:
  branches:
    include:
      - main

variables:
  Prefix: 'fayaz'
  Environment: 'staging'
  BuildConfiguration: 'release'
  ArtifactStagingDirectory: '$(Build.ArtifactStagingDirectory)'
  AzureSubscription: 'AzureSubscriptionConnection(25a98a18-5e94-4b21-9d17-e8cf45bfd81f)'
  WebAppName: '$(Prefix)-webapp'
  ResourceGroupName: '$(Prefix)-rg'
  SlotName: 'staging'
  PackagePath: '$(System.DefaultWorkingDirectory)/drop/WebApp.zip'

stages:
  - stage: Build_Stage
    displayName: Build Stage
    jobs:
      - job: Build_WebApp
        displayName: Build Web Application
        pool:
          vmImage: 'windows-2019'
          demands: java
        steps:
        - task: DotNetCoreCLI@2
          displayName: Restore Dependencies
          inputs:
            command: restore
            projects: '**/WebApp/WebApp.csproj'

        - task: DotNetCoreCLI@2
          displayName: Build Application
          inputs:
            command: build
            projects: '**/WebApp/WebApp.csproj'
            arguments: '--configuration $(BuildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: Run Unit Tests
          inputs:
            command: test
            projects: '**/*UnitTest*.csproj'
            arguments: '--configuration $(BuildConfiguration)'

        - task: DotNetCoreCLI@2
          displayName: Publish Application
          inputs:
            command: publish
            publishWebProjects: true
            arguments: '--configuration $(BuildConfiguration) --output $(ArtifactStagingDirectory)'
            zipAfterPublish: true

        - task: PublishBuildArtifacts@1
          displayName: Publish Application Artifact
          inputs:
            PathtoPublish: '$(ArtifactStagingDirectory)'
            ArtifactName: 'WebApp'

  - stage: Deploy_Stage
    displayName: Deploy Stage
    dependsOn: Build_Stage
    jobs:
      - job: Deploy_WebApp
        displayName: Deploy Web Application to Azure
        pool:
          vmImage: 'windows-2019'
        steps:
        - task: DownloadBuildArtifacts@0
          displayName: Download Build Artifacts
          inputs:
            artifactName: 'WebApp'
            downloadPath: '$(System.DefaultWorkingDirectory)'

        - task: AzureRmWebAppDeployment@4
          displayName: Deploy Web App to Staging Slot
          inputs:
            ConnectionType: AzureRM
            azureSubscription: $(AzureSubscription)
            appType: webApp
            WebAppName: $(WebAppName)
            deployToSlotOrASE: true
            ResourceGroupName: $(ResourceGroupName)
            SlotName: $(SlotName)
            packageForLinux: $(PackagePath)

  - stage: Swap_Slot_Stage
    displayName: Swap Slots
    dependsOn: Deploy_Stage
    jobs:
      - job: Swap_Slots
        displayName: Swap Staging Slot to Production
        pool:
          vmImage: 'windows-2019'
        steps:
        - task: AzureRmWebAppDeployment@4
          displayName: Swap Slots
          inputs:
            ConnectionType: AzureRM
            azureSubscription: $(AzureSubscription)
            appType: webApp
            WebAppName: $(WebAppName)
            ResourceGroupName: $(ResourceGroupName)
            Action: SwapSlots
            SourceSlot: $(SlotName)
            TargetSlot: 'production'

  - stage: Post_Deployment_Validation
    displayName: Post-Deployment Validation
    dependsOn: Swap_Slot_Stage
    jobs:
      - job: Validate_Deployment
        displayName: Validate Production Deployment
        pool:
          vmImage: 'windows-2019'
        steps:
        - task: PowerShell@2
          displayName: Validate Web App URL
          inputs:
            targetType: 'inline'
            script: |
              $url = "https://$(WebAppName).azurewebsites.net"
              Write-Host "Validating Web App URL: $url"
              $response = Invoke-WebRequest -Uri $url -UseBasicParsing
              if ($response.StatusCode -ne 200) {
                Write-Error "Web App validation failed with status code: $($response.StatusCode)"
              } else {
                Write-Host "Web App validated successfully."
              }
